import React,{useState,useEffect,useRef} from 'react';
import {Clock,ArrowLeft,ArrowRight,Trophy,ShieldCheck} from 'lucide-react';
import {Button,Modal} from './Shared';
import {isDemo,demoStore,updateDemo,getDemoQuestions,rpc} from '../lib';
import {demoQuestions} from '../data';
import {grade} from '../assessment';
export default function Exam({test,user,onClose,onComplete}){
 const [questions,setQuestions]=useState([]),[attempt,setAttempt]=useState(null),[answers,setAnswers]=useState({}),[index,setIndex]=useState(0),[remaining,setRemaining]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[confirm,setConfirm]=useState(false);
 const lock=useRef(false),saveQueue=useRef(Promise.resolve()),clockOffset=useRef(0);
 useEffect(()=>{let active=true;(async()=>{try{let a,qs;if(isDemo){qs=await getDemoQuestions(test.id);const d=demoStore();const previous=d.results.find(r=>r.test_id===test.id&&r.student_id===user.id);if(previous){if(active)setResult(previous);return;}a=d.attempts.find(a=>a.test_id===test.id&&a.student_id===user.id);if(!a){a={id:crypto.randomUUID(),test_id:test.id,student_id:user.id,deadline:new Date(Date.now()+test.duration_minutes*60000).toISOString(),answers:{}};updateDemo({attempts:[...d.attempts,a]})}}else{const data=await rpc('start_attempt',{p_test_id:test.id});a=data.attempt;qs=data.questions;clockOffset.current=new Date(data.server_time).getTime()-Date.now();if(a.status==='submitted'){if(active)setResult(a);return;}}if(active){setAttempt(a);setQuestions(qs);setAnswers(a.answers||{});}}catch(e){if(active)setError(e.message)}})();return()=>{active=false}},[test.id,user.id]);
 async function submit(){if(lock.current||!attempt||result)return;lock.current=true;setBusy(true);setConfirm(false);setError('');try{await saveQueue.current;let r;if(isDemo){const d=demoStore();const a=d.attempts.find(x=>x.id===attempt.id);const correct=d.answer_keys[test.id]||Object.fromEntries(demoQuestions.map(q=>[q.position,q.answer]));r={...grade(questions,a.answers,correct,test.marks_per_question,test.negative_marks),test_id:test.id,student_id:user.id,name:user.name,username:user.username};const existing=d.results.find(x=>x.test_id===test.id&&x.student_id===user.id);if(existing)r=existing;else updateDemo({results:[...d.results,r]})}else r=await rpc('submit_attempt',{p_attempt_id:attempt.id});setResult(r)}catch(e){setError('Submission not confirmed: '+e.message+'. Reconnect and retry. Your saved answers remain safe.')}finally{lock.current=false;setBusy(false)}}
 useEffect(()=>{if(!attempt||result)return;const tick=()=>{const secs=Math.max(0,Math.ceil((new Date(attempt.deadline).getTime()-Date.now()-clockOffset.current)/1000));setRemaining(secs);if(secs===0)submit()};tick();const t=setInterval(tick,1000);return()=>clearInterval(t)},[attempt,result,questions]);
 useEffect(()=>{const warn=e=>{if(attempt&&!result){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[attempt,result]);
 async function choose(value){if(saving||busy||remaining===0)return;const q=questions[index];setSaving(true);setError('');const job=(async()=>{try{if(isDemo){const d=demoStore();const a=d.attempts.find(a=>a.id===attempt.id);if(Date.now()>=new Date(a.deadline).getTime())throw Error('Time is over.');const next={...a.answers};if(value===null)delete next[q.id];else next[q.id]=value;updateDemo({attempts:d.attempts.map(x=>x.id===a.id?{...a,answers:next}:x)});setAnswers(next)}else{await rpc('save_answer',{p_attempt_id:attempt.id,p_question_id:q.id,p_choice:value});setAnswers(prev=>{const next={...prev};if(value===null)delete next[q.id];else next[q.id]=value;return next})}}catch(e){setError('Answer was not saved: '+e.message+' Select the option again to retry.')}finally{setSaving(false)}})();saveQueue.current=job;await job;}
 const q=questions[index];
 return <div className="exam-backdrop" role="dialog" aria-modal="true" aria-label="Timed examination"><header className="exam-header"><div><h2>{test.title}</h2><p>{user.name} · {user.username} {isDemo?'· Preview test':''}</p></div>{!result&&<div className={`exam-timer ${remaining<60?'danger-text':''}`}><Clock size={20}/>{remaining===null?'—:—':`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`}</div>}</header>
 {result?<div className="result-card"><Trophy size={46}/><h2>A step forward. Well done!</h2><p>Your test has been submitted and graded{isDemo?' in preview mode':''}.</p><div className="result-stats"><div><strong className="green">{result.right_count}</strong><small>Correct answers</small></div><div><strong className="red">{result.wrong_count}</strong><small>Wrong answers</small></div><div><strong>{result.score}</strong><small>Total score</small></div></div><Button onClick={onComplete}>View my rank <ArrowRight size={17}/></Button><Button className="secondary" onClick={onClose}>Back to learning</Button></div>:q?<div className="exam-main"><div><article className="question-card"><span>QUESTION {index+1} OF {questions.length}</span><h3>{q.question}</h3><div className="options">{q.options.map((o,i)=><button className={`option ${answers[q.id]===i?'selected':''}`} key={i} onClick={()=>choose(i)} disabled={saving||busy||remaining===0}><span>{'ABCD'[i]}</span>{o}</button>)}</div><div className="save-status">{saving?'Saving your answer…':Object.hasOwn(answers,q.id)?'Answer saved.':'Select an option to save your answer.'}</div>{Object.hasOwn(answers,q.id)&&<button className="text-button" disabled={saving||busy||remaining===0} onClick={()=>choose(null)}>Clear answer</button>}<div className="exam-navigation"><Button className="secondary" onClick={()=>setIndex(index-1)} disabled={index===0}><ArrowLeft size={15}/>Previous</Button><Button onClick={()=>index<questions.length-1?setIndex(index+1):setConfirm(true)}>{index<questions.length-1?'Next question':'Review & submit'}<ArrowRight size={15}/></Button></div></article>{error&&<div className="alert error" role="alert">{error}</div>}</div><aside className="question-palette"><h3>Your question map</h3><div>{questions.map((q,i)=><button key={q.id} className={`${Object.hasOwn(answers,q.id)?'answered':''} ${i===index?'current':''}`} onClick={()=>setIndex(i)}>{i+1}</button>)}</div><p>{Object.keys(answers).length} of {questions.length} answered</p><p><ShieldCheck size={13}/> Answers are saved before grading.</p><Button loading={busy} disabled={saving} onClick={()=>remaining===0?submit():setConfirm(true)}>Submit test</Button><button className="text-button" style={{marginTop:18}} onClick={()=>{if(window.confirm('Leave this test? The timer will keep running. You can reopen it before the deadline.'))onClose()}}>Leave test</button></aside></div>:<div className="container page-content">{error?<><div className="alert error">{error}</div><Button onClick={onClose}>Go back</Button></>:<p>Preparing your test securely…</p>}</div>}
 {confirm&&<Modal title="Ready to submit?" onClose={()=>setConfirm(false)}><p className="muted">You have answered {Object.keys(answers).length} of {questions.length} questions. Once submitted, this attempt cannot be changed.</p><div className="hero-buttons"><Button loading={busy} disabled={saving} onClick={submit}>Submit my answers</Button><button className="text-button" onClick={()=>setConfirm(false)}>Keep working</button></div></Modal>}
 </div>;
}
