import React,{useState,useEffect,lazy,Suspense} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Clock,Play,Check,ChevronLeft,ChevronRight,GraduationCap,Target,Landmark,Building2,Users,Trophy,Sparkles,Menu,X,MapPin,Phone,Mail,Instagram,Youtube,Facebook,Send,ShieldCheck,FileText,LogOut,ChevronDown,MonitorPlay,CheckCircle2} from 'lucide-react';
import {defaultSettings} from './data';
import {loadPublic,isDemo,supabase,query,safeUrl,leaderboard} from './lib';
import {Brand,Button,Modal,SectionTitle,Empty} from './components/Shared';
import Auth from './components/Auth';
const Admin=lazy(()=>import('./components/Admin'));
const Exam=lazy(()=>import('./components/Exam'));
const Learning=lazy(()=>import('./components/Learning'));
const icons={target:Target,landmark:Landmark,building:Building2};
function CourseCard({batch,onOpen}){const Icon=icons[batch.icon]||BookOpen;return <article className="course-card"><div className={`course-art ${batch.color||'peach'}`} style={batch.image_url?{backgroundImage:`url(${safeUrl(batch.image_url)})`,backgroundSize:'cover'}:{}}><span className="course-badge">{batch.badge||'LEARN WITH SURE60'}</span><div className="art-content"><span className="art-kicker">SURE60 LEARNING PROGRAM</span><h3>{batch.category==='SSC Exams'?<>Aim higher.<br/>Go further.</>:batch.category==='State Exams'?<>Made for your<br/>next chapter.</>:<>A smarter start.<br/>A brighter future.</>}</h3><span className="art-sub">{batch.category} preparation, simplified.</span></div><div className="course-art-icon"><Icon strokeWidth={1.25}/></div><span className="art-dots">•••</span></div><div className="course-body"><div className="card-meta"><span><span className="live-dot"/>{batch.format}</span><span>{batch.language}</span></div><h3>{batch.name}</h3><p>{batch.subtitle}</p><div className="subject-tags">{(batch.subjects||[]).slice(0,3).map(x=><span key={x}>{x}</span>)}{batch.subjects?.length>3&&<span>+{batch.subjects.length-3}</span>}</div><div className="course-bottom"><span><BookOpen size={15}/> Learn at your pace</span><button onClick={()=>onOpen(batch)}>Explore batch <ArrowUpRight size={17}/></button></div></div></article>}
export default function App(){const [settings,setSettings]=useState(defaultSettings),[batches,setBatches]=useState([]),[tests,setTests]=useState([]),[user,setUser]=useState(null),[page,setPage]=useState('home'),[auth,setAuth]=useState(null),[slide,setSlide]=useState(0),[filter,setFilter]=useState('All batches'),[menu,setMenu]=useState(false),[modal,setModal]=useState(null),[ranks,setRanks]=useState([]),[error,setError]=useState(''),[toast,setToast]=useState(''),[exam,setExam]=useState(null),[rankLoading,setRankLoading]=useState(false),[reset,setReset]=useState(false),[password,setPassword]=useState('');
async function refresh(){try{const d=await loadPublic();setSettings(d.settings);setBatches(d.batches);setTests(d.tests)}catch(e){setError('Unable to load content. Check your Supabase setup: '+e.message)}}
useEffect(()=>{refresh();if(!isDemo){supabase.auth.getSession().then(async({data})=>{if(data.session){const p=await query('profiles',{id:data.session.user.id});if(p[0]?.approved)setUser(p[0]);else if(!location.hash.includes('reset-password'))await supabase.auth.signOut()}}).catch(e=>setError(e.message));const {data:{subscription}}=supabase.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')setReset(true);if(event==='SIGNED_OUT')setUser(null)});return()=>subscription.unsubscribe()}},[]);
useEffect(()=>{if(location.pathname==='/avinash')setAuth('admin');},[]);
useEffect(()=>{const t=setInterval(()=>setSlide(s=>(s+1)%Math.max(1,settings.hero_slides.length)),6500);return()=>clearInterval(t)},[settings.hero_slides.length]);
useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)},[toast]);
useEffect(()=>{const io=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');io.unobserve(x.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));return()=>io.disconnect()},[batches,page]);
function navigate(p,anchor){setPage(p);setMenu(false);if(anchor)setTimeout(()=>document.getElementById(anchor)?.scrollIntoView({behavior:'smooth'}),60);else window.scrollTo({top:0,behavior:'smooth'})}
function protectedNav(p){if(!user){setAuth('student');return;}navigate(p)}
async function showRanks(test){setModal({type:'ranks',test});setRanks([]);setRankLoading(true);try{setRanks(await leaderboard(test.id))}catch(e){setToast(e.message)}finally{setRankLoading(false)}}
async function signOut(){if(!isDemo)await supabase.auth.signOut();setUser(null);navigate('home')}
function startTest(test){if(!user){setAuth('student');return;}setModal({type:'test',test})}
const current=settings.hero_slides[slide%settings.hero_slides.length]||defaultSettings.hero_slides[0];
return <><div className="announcement"><span><Sparkles size={13}/>{settings.announcement}</span><button onClick={()=>navigate('home','batches')}>Find your batch <ArrowRight size={13}/></button></div><header className="site-header"><div className="container nav-inner"><Brand settings={settings} onClick={()=>navigate('home')}/><nav className={menu?'open':''} aria-label="Main navigation"><button className={page==='home'?'active':''} onClick={()=>navigate('home')}>Home</button><button onClick={()=>navigate('home','batches')}>Our Batches <ChevronDown size={13}/></button><button className={page==='tests'?'active':''} onClick={()=>navigate('tests')}>Test Series</button><button className={page==='learning'?'active':''} onClick={()=>protectedNav('learning')}>My Learning</button><button onClick={()=>navigate('home','about')}>About Us</button></nav><div className="nav-actions">{user?<><button className="user-pill" onClick={()=>protectedNav(user.role==='admin'?'admin':'learning')}><span>{user.name.charAt(0)}</span>{user.name.split(' ')[0]}</button><button className="icon-button logout" onClick={signOut} aria-label="Sign out"><LogOut size={19}/></button></>:<Button onClick={()=>setAuth('student')} className="nav-login">Student Login <ArrowUpRight size={16}/></Button>}<button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></div></div></header>
{error&&<div className="container alert error">{error}<button onClick={refresh}>Retry</button></div>}
<Suspense fallback={<div className="empty">Loading your learning space…</div>}>
{page==='admin'&&user?.role==='admin'?<Admin user={user} settings={settings} onRefresh={refresh} notify={setToast}/>:page==='learning'&&user?<Learning user={user} batches={batches} onTests={()=>navigate('tests')}/>:page==='tests'?<main className="container page-content"><SectionTitle label="PRACTICE. IMPROVE. REPEAT." title="Your next challenge awaits." subtitle="Take a timed test, understand your progress, and find your place on the leaderboard."/>{isDemo&&<div className="alert info">Preview mode: sample tests and illustrative leaderboard data. Your preview results are saved in this browser.</div>}<div className="test-list">{tests.filter(t=>t.enabled).map(t=><article className="test-list-card" key={t.id}><span className="test-icon"><FileText/></span><div><span className="eyebrow">{t.category}</span><h3>{t.title}</h3><p>{t.total_questions} questions · {t.duration_minutes} minutes · {t.marks_per_question} marks each</p></div><div className="test-actions"><Button onClick={()=>startTest(t)}>Start test <ArrowRight size={16}/></Button><button className="text-button" onClick={()=>showRanks(t)}><Trophy size={16}/> Leaderboard</button></div></article>)}</div>{!tests.length&&<Empty title="New challenges are on the way" description="Your admin will publish tests here soon."/>}</main>:<main>
<section className="hero container"><div className="hero-copy" key={slide}><div className="hero-eyebrow"><span/> {current.eyebrow}</div><h1>{current.title.split('\n').map((line,i)=><React.Fragment key={i}>{line}<br/></React.Fragment>)}<span>{current.highlight}<svg viewBox="0 0 400 20" preserveAspectRatio="none"><path d="M4 12Q175 -3 395 7M24 18Q200 5 370 13"/></svg></span></h1><p>{current.description}</p><div className="hero-buttons"><Button onClick={()=>navigate('home','batches')}>Explore Our Batches <ArrowUpRight size={19}/></Button><button className="watch-button" onClick={()=>setModal({type:'journey'})}><span><Play size={16} fill="currentColor"/></span>Discover Sure60</button></div><div className="hero-trust"><div className="avatar-stack"><span>AK</span><span>PS</span><span>RV</span><span>YOU</span></div><div><strong>A community that grows together</strong><small>Your goals. Our shared journey.</small></div></div></div><div className="hero-visual"><div className="hero-outline"/><span className="star-doodle">✳</span><div className="hero-photo"><img src={safeUrl(settings.hero_image)||settings.hero_image||'/students.jpg'} alt="Students studying together at a table"/><div className="photo-shade"/><div className="photo-caption"><span>MORE THAN A CLASSROOM</span><h3>A place to find<br/>your potential.</h3></div><div className="photo-label"><span className="live-dot"/> YOUR FUTURE STARTS HERE</div></div><div className="floating-card mentor-float"><span><GraduationCap size={24}/></span><div><strong>The right guidance</strong><small>Every step of the way</small></div><CheckCircle2 size={17}/></div><div className="floating-card progress-float"><div className="mini-chart"><i/><i/><i/><i/></div><div><strong>Better every day.</strong><small>Small steps. Big possibilities.</small></div><span className="growth">↗</span></div><span className="dot-grid"/></div><div className="slider-control"><span className="slide-count">0{slide+1}<small> / 0{settings.hero_slides.length}</small></span><div className="slide-dots">{settings.hero_slides.map((_,i)=><button key={i} className={i===slide?'selected':''} onClick={()=>setSlide(i)} aria-label={`Show slide ${i+1}`}/>)}</div><div className="slide-arrows"><button onClick={()=>setSlide((slide+settings.hero_slides.length-1)%settings.hero_slides.length)} aria-label="Previous slide"><ChevronLeft size={17}/></button><button onClick={()=>setSlide((slide+1)%settings.hero_slides.length)} aria-label="Next slide"><ChevronRight size={17}/></button></div></div></section>
<section className="benefit-strip"><div className="container benefits"><div><span className="benefit-icon peach"><GraduationCap/></span><div><strong>Guidance that matters</strong><p>Learn from dedicated educators</p></div></div><div><span className="benefit-icon mint"><MonitorPlay/></span><div><strong>Your pace. Your place.</strong><p>Classes that fit your learning journey</p></div></div><div><span className="benefit-icon lavender"><Target/></span><div><strong>Practice with purpose</strong><p>Mock tests with meaningful insights</p></div></div><div><span className="benefit-icon yellow"><Users/></span><div><strong>Never learn alone</strong><p>A community that supports you</p></div></div></div></section>
<section className="container section reveal" id="batches"><SectionTitle label="FIND YOUR DIRECTION" title="Big dreams start with the right batch." subtitle="Purpose-built programs. Clear concepts. One step closer to your goal." action="View all batches" onAction={()=>{setFilter('All batches');document.getElementById('batch-grid')?.scrollIntoView({behavior:'smooth',block:'center'})}}/><div className="filter-tabs">{['All batches','SSC Exams','State Exams','Banking'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='All batches'&&<span className="grid-mini">▦</span>}{f}</button>)}</div><div className="course-grid" id="batch-grid">{batches.filter(b=>b.enabled&&(filter==='All batches'||b.category===filter)).map(b=><CourseCard key={b.id} batch={b} onOpen={b=>setModal({type:'batch',batch:b})}/>)}</div>{!batches.filter(b=>b.enabled&&(filter==='All batches'||b.category===filter)).length&&<Empty title="Something good is on its way" description="New batches will appear here as soon as they are published."/>}<p className="section-footnote"><ShieldCheck size={15}/> A focused learning experience, from your first class to your next milestone.</p></section>
<section className="test-section reveal"><div className="container"><div className="test-feature"><div className="test-feature-copy"><span className="dark-eyebrow"><span/> READY TO CHALLENGE YOURSELF?</span><h2>A little practice.<br/>A lot of <span>possibility.</span></h2><p>Put your preparation to the test. Compete, learn from<br className="desktop-only"/> your mistakes, and come back stronger.</p><div className="test-points"><span><Check size={15}/> Timed mock tests</span><span><Check size={15}/> Instant results</span><span><Check size={15}/> Live rankings</span></div><Button onClick={()=>navigate('tests')}>Explore Test Series <ArrowUpRight size={18}/></Button></div><div className="featured-test"><div className="featured-test-top"><span><span className="live-dot"/> {tests[0]?.label||'YOUR NEXT CHALLENGE'}</span><span className="test-icon"><FileText size={22}/></span></div><h3>{tests[0]?.title||'Prepare for your next test'}</h3><p>{tests[0]?.description||'New tests will be published here soon.'}</p><div className="test-stats"><div><BookOpen size={17}/><strong>{tests[0]?.total_questions||'—'}</strong><small>Questions</small></div><div><Clock size={17}/><strong>{tests[0]?.duration_minutes||'—'} min</strong><small>Duration</small></div><div><Trophy size={17}/><strong>{tests[0]?tests[0].total_questions*tests[0].marks_per_question:'—'}</strong><small>Total marks</small></div></div><Button className="full" disabled={!tests[0]} onClick={()=>startTest(tests[0])}>Take the challenge <ArrowRight size={18}/></Button><button className="leaderboard-link" disabled={!tests[0]} onClick={()=>showRanks(tests[0])}><Trophy size={14}/> View leaderboard <ChevronRight size={14}/></button></div></div></div></section>
<section className="container section reveal" id="about"><SectionTitle label="THE SURE60 DIFFERENCE" title="Not just preparation. A partnership." subtitle="The right environment can change everything. We’re here to help you find yours."/><div className="why-grid">{[{icon:BookOpen,title:'Clarity over complexity',text:'Concepts explained simply. Structured lessons that build confidence, one topic at a time.',color:'peach',n:'01'},{icon:Target,title:'Progress you can see',text:'Meaningful practice and honest feedback. Understand your strengths and what to work on next.',color:'mint',n:'02'},{icon:Users,title:'People who believe in you',text:'A supportive learning space with guidance that keeps you moving toward your goals.',color:'lavender',n:'03'}].map(({icon:Icon,...x})=><article className="why-card" key={x.n}><div><span className={`benefit-icon ${x.color}`}><Icon/></span><small>{x.n}</small></div><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></section>
<section className="container campus-section reveal"><div className="campus-art"><span className="campus-orbit"/><Landmark size={94} strokeWidth={1}/><span className="campus-pin"><MapPin size={22}/></span><span className="campus-caption">ROOTED IN KARNAL. REACHING FOR MORE.</span></div><div className="campus-copy"><span className="eyebrow">YOUR NEIGHBOURHOOD. YOUR NEXT CHAPTER.</span><h2>Online convenience.<br/>A real campus connection.</h2><p>Come say hello at our Karnal campus. Let’s talk about your goals and find the right path forward, together.</p><div className="campus-address"><MapPin size={18}/>{settings.address}</div><a className="text-button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(settings.address)}`} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={17}/></a></div></section>
<section className="container cta-section reveal"><div><span>YOUR JOURNEY IS JUST GETTING STARTED</span><h2>Let’s make your next chapter count.</h2><p>Bring your ambition. We’ll bring the guidance.</p></div><Button onClick={()=>user?protectedNav('learning'):setAuth('student')}>Start Learning Today <ArrowUpRight size={19}/></Button><span className="cta-spark">✳</span></section></main>}
</Suspense>
<footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><Brand settings={settings} onClick={()=>navigate('home')}/><p>A little guidance. A big future.<br/>Your learning journey, our shared purpose.</p><div className="social-links">{[['instagram',Instagram],['youtube',Youtube],['facebook',Facebook],['telegram',Send]].map(([k,Icon])=>safeUrl(settings[k])?<a key={k} href={safeUrl(settings[k])} aria-label={k} target="_blank" rel="noreferrer"><Icon size={18}/></a>:<button key={k} aria-label={k} onClick={()=>setToast('Our '+k+' link will be announced soon.')}><Icon size={18}/></button>)}</div></div><div><h4>Explore Sure60</h4><button onClick={()=>navigate('home','batches')}>Our Batches</button><button onClick={()=>navigate('tests')}>Test Series</button><button onClick={()=>navigate('home','about')}>About Us</button><button onClick={()=>protectedNav('learning')}>My Learning</button></div><div><h4>Here to help</h4><button onClick={()=>setModal({type:'faq'})}>Frequently asked questions</button><button onClick={()=>setModal({type:'contact'})}>Contact us</button><button onClick={()=>setModal({type:'privacy'})}>Privacy policy</button><button onClick={()=>setModal({type:'terms'})}>Terms of use</button></div><div className="footer-contact"><h4>Come find us</h4><p><MapPin size={17}/>{settings.address}</p>{settings.phone&&<a href={`tel:${settings.phone}`}><Phone size={16}/>{settings.phone}</a>}{settings.email&&<a href={`mailto:${settings.email}`}><Mail size={16}/>{settings.email}</a>}<span className="campus-tag"><span className="live-dot"/> A place to learn. A space to grow.</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Sure60. All rights reserved.</span><span>Built for big dreams.{isDemo&&<small> Preview · sample content</small>}</span>{settings.admin_enabled&&<button onClick={()=>user?.role==='admin'?navigate('admin'):setAuth('admin')}>Avinash <ArrowUpRight size={12}/></button>}</div></footer>
{auth&&<Auth admin={auth==='admin'} onClose={()=>setAuth(null)} onLogin={u=>{setUser(u);setToast(`Welcome, ${u.name}!`);navigate(u.role==='admin'?'admin':'learning')}}/>}
{exam&&<Suspense fallback={null}><Exam test={exam} user={user} onClose={()=>setExam(null)} onComplete={()=>{setExam(null);showRanks(exam)}}/></Suspense>}
{modal&&<Modal title={modal.type==='batch'?modal.batch.name:modal.type==='ranks'?modal.test.title+' • Leaderboard':modal.type==='test'?'Ready when you are.':modal.type==='faq'?'A little clarity, before you begin':modal.type==='contact'?'Let’s talk about your next step':modal.type==='privacy'?'Your privacy matters':modal.type==='terms'?'Learning together, responsibly':'Welcome to the Sure60 way'} onClose={()=>setModal(null)} wide={modal.type==='ranks'}>
{modal.type==='batch'&&<div className="detail-content"><span className="pill">{modal.batch.category}</span><p>{modal.batch.description}</p><h4>What you’ll learn</h4><div className="subject-tags">{modal.batch.subjects?.map(s=><span key={s}><Check size={14}/>{s}</span>)}</div><div className="alert info">Batch access is enabled by your admin after your account is verified.</div><Button onClick={()=>{setModal(null);protectedNav('learning')}}>Go to My Learning <ArrowRight size={18}/></Button></div>}
{modal.type==='test'&&<div className="detail-content"><p>{modal.test.title}</p><div className="instruction-grid"><span><Clock/> {modal.test.duration_minutes} minutes</span><span><BookOpen/> {modal.test.total_questions} questions</span></div><ul className="instruction-list"><li>Each correct answer earns {modal.test.marks_per_question} marks.</li><li>Each wrong answer deducts {modal.test.negative_marks} marks. Unanswered questions earn 0.</li><li>Your timer starts immediately and continues even if you close the page.</li><li>Saved answers are submitted automatically when time runs out. One attempt per student.</li><li>Your name, roll number and score appear on the leaderboard after submission.</li></ul><Button onClick={()=>{setExam(modal.test);setModal(null)}}>Start my test <ArrowRight size={18}/></Button></div>}
{modal.type==='ranks'&&<div className="detail-content"><div className="leaderboard-heading"><Trophy/><div><h3>Every attempt is a step forward.</h3><p>{ranks.length} completed attempts {isDemo?'· illustrative preview rankings':''}</p></div></div>{rankLoading?<p>Loading live rankings…</p>:ranks.length?<div className="table-scroll"><table><thead><tr><th>Rank</th><th>Student</th><th>Roll number</th><th>Correct</th><th>Wrong</th><th>Score</th></tr></thead><tbody>{ranks.map((r,i)=><tr key={i}><td><span className={`rank rank-${r.rank}`}>{r.rank}</span></td><td><strong>{r.name}</strong></td><td>{r.username}</td><td className="green">{r.right_count}</td><td className="red">{r.wrong_count}</td><td><strong>{r.score}</strong></td></tr>)}</tbody></table></div>:<Empty title="Be the first to take the challenge" description="Completed attempts appear here automatically."/>}</div>}
{modal.type==='journey'&&<div className="detail-content"><img className="journey-image" src="/students.jpg" alt="Students learning together"/><h3>Your ambition has a home here.</h3><p>Sure60 brings structured preparation, accessible lessons and purposeful practice into one learning space. Join a batch, follow your subject-wise classes, and build confidence with every test.</p><Button onClick={()=>{setModal(null);navigate('home','batches')}}>Find your batch <ArrowRight size={18}/></Button></div>}
{modal.type==='faq'&&<div className="faq-list">{[['How do I join Sure60?','Create a student account using your email and roll number. The admin will verify your registration before you can access your learning space.'],['Where will my classes appear?','Verified students can open My Learning. Batches enabled by the admin appear with subject-wise video lessons and linked PDFs.'],['How do mock tests work?','Start a test to begin the countdown. Your answers are saved as you go. Submit early or let the timer finish; your result is calculated and ranked.'],['Can I use my phone?','Yes. The website, lessons and tests are designed for phones, tablets and computers. A stable internet connection is required for tests.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>}
{modal.type==='contact'&&<div className="detail-content"><p>Visit us at <strong>{settings.address}</strong>.</p>{settings.phone?<a className="button" href={`tel:${settings.phone}`}><Phone size={17}/>Call {settings.phone}</a>:<p>Phone and email details will be added by the campus team soon. In the meantime, visit our Karnal campus.</p>}{settings.email&&<p><a href={`mailto:${settings.email}`}>{settings.email}</a></p>}</div>}
{modal.type==='privacy'&&<div className="detail-content"><p>We use your name, email and roll number to manage your account, verify access and deliver your classes. Test answers and scores are stored to track assessment results.</p><p>Your name, roll number and scores are visible on test leaderboards. Passwords are managed by Supabase Authentication, not stored in readable form by Sure60. Embedded YouTube videos and Google Fonts may contact their respective services.</p><p>Contact the campus to request account correction or deletion. In preview mode, sample account data and results are stored only in your browser. Clear your browser storage to remove them.</p></div>}
{modal.type==='terms'&&<div className="detail-content"><p>Use your own verified account. Do not share credentials, redistribute class materials, or manipulate test submissions. Access to batches is granted by the administrator.</p><p>Tests require an active internet connection; only answers received by the server before the deadline are graded. Courses provide preparation support, not a guarantee of selection or employment.</p><p>Preview content is illustrative. Confirm current batch details and availability directly with the Karnal campus.</p></div>}
</Modal>}
{reset&&<Modal title="Choose a new password" onClose={()=>setReset(false)}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const {error}=await supabase.auth.updateUser({password});if(error)setToast(error.message);else{setReset(false);setToast('Password updated.');history.replaceState(null,'','/')}}}><label>New password<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><Button>Update password</Button></form></Modal>}
{toast&&<div className="toast" role="status"><CheckCircle2 size={20}/>{toast}<button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={16}/></button></div>}
</>}
