import {createClient} from '@supabase/supabase-js';
import {defaultSettings,demoBatches,demoTests,demoLessons,demoRanks,demoQuestions} from './data';
const url=import.meta.env.VITE_SUPABASE_URL, key=import.meta.env.VITE_SUPABASE_ANON_KEY;
export const isDemo=!url||!key;
export const supabase=isDemo?null:createClient(url,key);
const initial={settings:defaultSettings,batches:demoBatches,tests:demoTests,lessons:demoLessons,profiles:[{id:'demo-student',name:'Demo Student',username:'demo',email:'student@example.com',approved:true,role:'student'},{id:'pending-demo',name:'New Student',username:'S60-1091',email:'pending@example.com',approved:false,role:'student'}],enrollments:[{student_id:'demo-student',batch_id:'ssc'},{student_id:'demo-student',batch_id:'cet'}],results:[],questions:{},answer_keys:{},attempts:[]};
export function demoStore(){try{return {...structuredClone(initial),...JSON.parse(localStorage.getItem('sure60-data-v1')||'{}')}}catch{return structuredClone(initial)}}
export function updateDemo(data){localStorage.setItem('sure60-data-v1',JSON.stringify({...demoStore(),...data}));}
export async function query(table,options={}){if(isDemo)return demoStore()[table]||[];let q=supabase.from(table).select('*');for(const [k,v] of Object.entries(options))q=q.eq(k,v);const {data,error}=await q;if(error)throw error;return data;}
export async function saveRow(table,row){if(isDemo){let data=demoStore()[table]||[];const next={...row,id:row.id||crypto.randomUUID()};data=data.some(x=>x.id===next.id)?data.map(x=>x.id===next.id?next:x):[...data,next];updateDemo({[table]:data});return next;}const {data,error}=await supabase.from(table).upsert(row).select().single();if(error)throw error;return data;}
export async function deleteRow(table,id){if(isDemo){updateDemo({[table]:demoStore()[table].filter(x=>x.id!==id)});return;}const {error}=await supabase.from(table).delete().eq('id',id);if(error)throw error;}
export async function loadPublic(){if(isDemo){const d=demoStore();return {settings:d.settings,batches:d.batches,tests:d.tests}}const [settings,batches,tests]=await Promise.all([query('site_settings'),query('batches'),query('tests')]);return {settings:{...defaultSettings,...settings[0]?.value},batches,tests};}
export async function rpc(name,args){const {data,error}=await supabase.rpc(name,args);if(error)throw error;return data;}
export async function login(identifier,password,admin=false){if(isDemo){if(admin&&identifier==='avinash'&&password==='Sure60@Demo')return {id:'demo-admin',name:'Avinash',username:'avinash',role:'admin',approved:true};if(!admin&&identifier==='demo'&&password==='Student@60')return demoStore().profiles[0];throw Error('Use the preview credentials shown below.');}
 let data,error;if(identifier.includes('@')){({data,error}=await supabase.auth.signInWithPassword({email:identifier,password}));}else{const res=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:identifier,password})});const result=await res.json();if(!res.ok)throw Error(result.error||'Unable to sign in.');({data,error}=await supabase.auth.setSession(result));}if(error)throw error;const p=await query('profiles',{id:data.user.id});if(!p[0]?.approved||(admin&&p[0].role!=='admin')){await supabase.auth.signOut();throw Error('Your account is awaiting admin verification, or does not have access.');}return p[0];}
export async function register(form){if(isDemo){await saveRow('profiles',{name:form.name,username:form.username,email:form.email,role:'student',approved:false});return;}const {error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{name:form.name,username:form.username.toLowerCase()},emailRedirectTo:location.origin}});if(error)throw error;await supabase.auth.signOut();}
export async function leaderboard(testId){if(isDemo)return [...demoRanks,...demoStore().results.filter(r=>r.test_id===testId)].sort((a,b)=>b.score-a.score||b.right_count-a.right_count).map((r,i)=>({...r,rank:i+1}));return rpc('get_leaderboard',{p_test_id:testId});}
export function safeUrl(input){try{const u=new URL(input);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
export function youtubeId(input){try{const u=new URL(input);if(u.hostname==='youtu.be')return /^[\w-]{11}$/.test(u.pathname.slice(1))?u.pathname.slice(1):'';if(!['youtube.com','www.youtube.com','m.youtube.com','www.youtube-nocookie.com'].includes(u.hostname))return '';const id=u.searchParams.get('v')||u.pathname.split('/').pop();return /^[\w-]{11}$/.test(id)?id:''}catch{return ''}}
export async function getDemoQuestions(testId){return (demoStore().questions[testId]||demoQuestions).map(({answer,...q})=>q)}
